[package]
name = "fluent_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
regex = "1.6.0"
rouille = "3.5.0"
serde = "1.0.144"
serde_json = "1.0.85"
